name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python: [3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m poetry install
      - uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pip
          key: ${{ matrix.os }}-pip-${{ secrets.CACHE_SEED }}-${{ matrix.python }}-${{ hashFiles('./poetry.lock') }}
          restore-keys: ${{ matrix.os }}-pip-${{ secrets.CACHE_SEED }}-${{ matrix.python }}-
      - name: Test
        run: |
          poetry run coverage run --module pytest
      - name: Verify test coverage
        run: |
          poetry run coverage xml
      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
